server:
  port : 8095
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydbdos?useSSL=false
    username: root
    password: root23612
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
        
  thymeleaf:
    cache: false
